version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/traefik"
    schedule:
      interval: "daily"
    assignees:
    - "dotKuro"
  - package-ecosystem: "docker"
    directory: "/nextcloud/mariadb"
    schedule:
      interval: "daily"
    assignees:
    - "dotkuro"
  - package-ecosystem: "docker"
    directory: "/nextcloud/redis"
    schedule:
      interval: "daily"
    assignees:
    - "dotKuro"
  - package-ecosystem: "docker"
    directory: "/nextcloud/nextcloud"
    schedule:
      interval: "daily"
    assignees:
    - "dotKuro"
