version: "3"

networks:
  exposed:
    external: true

services:
  mariadb:
    build: ./mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
     - ./mariadb/volume/:/var/lib/mysql/
    env_file:
     - ./mariadb/secret.env
    environment:
     - MYSQL_DATABASE=nextcloud
     - MYSQL_USER=nextcloud
  
  redis:
    build: ./redis
    restart: always

  nextcloud:
    build: ./nextcloud
    restart: always
    volumes:
      - ./nextcloud/volume/:/var/www/html/
    env_files:
     - ./mariadb/secret.env
    environment:
     - MYSQL_HOST=mariadb
     - REDIS_HOST=redis
     - MYSQL_DATABASE=nextcloud
     - MYSQL_USER=nextcloud
     - OVERWRITEPROTOCOL=https
     - OVERWRITEHOST=cloud.${DOMAIN}
    depends_on:
     - mariadb
     - redis
    network:
      - default
      - exposed
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud.rule=Host(`cloud.${DOMAIN}`)"
      - "traefik.http.routers.nextcloud.entrypoints=websecure"
      - "traefik.http.routers.nextcloud.tls.certresolver=global"
      - "traefik.http.services.nextcloud.loadbalancer.server.port=80"
      - "traefik.docker.network=exposed"

  cron:
    build: ./nextcloud
    restart: always
    volumes:
     - ./nextcloud/volume/:/var/www/html/
    entrypoint: /cron.sh
    depends_on:
      - mariadb
      - redis
  

