version: "3"

networks:
  exposed:
    external: true

services:
  mariadb:
    build: ./mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
     - ./mariadb/volume/:/var/lib/mysql/
    env_file:
     - ./mariadb/secret.env
    environment:
     - MYSQL_DATABASE=nextcloud
     - MYSQL_USER=nextcloud
  
  redis:
    build: ./redis
    restart: always


